Layers and Activations with torch.nn


In [4]:
import torch
from torch import nn

Linear Regression

In [22]:
class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.func = nn.Linear(1,1)
  def forward(self,x):
    return self.func(x)

clfL = LinearRegression()
print(clf)

Perceptron(
  (func): Linear(in_features=1, out_features=1, bias=True)
  (activation): Sigmoid()
)


In [23]:
x = torch.randn(1000,1)

In [25]:
x[0]

tensor([0.6067])

In [24]:
clfL(x[0])

tensor([0.4090], grad_fn=<ViewBackward0>)

Perceptron

In [26]:
class Perceptron(nn.Module):
  def __init__(self):
    super().__init__()
    self.func = nn.Linear(1,1)
    self.activation = nn.Sigmoid()
  def forward(self,x):
    return self.func(x)

clf = Perceptron()
print(clf)

Perceptron(
  (func): Linear(in_features=1, out_features=1, bias=True)
  (activation): Sigmoid()
)


In [27]:
clf(x[0])

tensor([0.5592], grad_fn=<ViewBackward0>)

Multi Layer Perceptron

In [36]:
class MLP(nn.Module):
  def __init__(self):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(1,3),
        nn.Sigmoid(),
        nn.Linear(3,5),
        nn.Sigmoid(),
        nn.Linear(5,1),
    )

  def forward(self,x):
    return self.layers(x)

clfm= MLP()
clfm

MLP(
  (layers): Sequential(
    (0): Linear(in_features=1, out_features=3, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=3, out_features=5, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=5, out_features=1, bias=True)
  )
)

In [37]:
clfm(x[0])

tensor([-0.0879], grad_fn=<ViewBackward0>)

In [33]:
x[0].shape

torch.Size([1])

Compare normal nn to functional. It is also called MODULE vs FUNCTIONAL API

In [41]:
from torch.nn import functional

functional.sigmoid(torch.Tensor([0]))

tensor([0.5000])

In [44]:
nn.Sigmoid()(torch.Tensor([0]))

tensor([0.5000])